//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIF2SVG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIF2SVG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building SVG....
        /// </summary>
        internal static string Converter_BuildSVG_Building_SVG {
            get {
                return ResourceManager.GetString("Converter_BuildSVG_Building_SVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Complete!.
        /// </summary>
        internal static string Converter_Cleanup_Conversion_Complete {
            get {
                return ResourceManager.GetString("Converter_Cleanup_Conversion_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data....
        /// </summary>
        internal static string Converter_Convert_Getting_data {
            get {
                return ResourceManager.GetString("Converter_Convert_Getting_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string Converter_Converter_Converting {
            get {
                return ResourceManager.GetString("Converter_Converter_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting frames....
        /// </summary>
        internal static string Converter_ExtractFramesAsync_Extracting_frames {
            get {
                return ResourceManager.GetString("Converter_ExtractFramesAsync_Extracting_frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ffmpeg {
            get {
                object obj = ResourceManager.GetObject("ffmpeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ffplay {
            get {
                object obj = ResourceManager.GetObject("ffplay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ffprobe {
            get {
                object obj = ResourceManager.GetObject("ffprobe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the absolute path of the directory your .gif files are stored in.
        /// </summary>
        internal static string Main_Start_Enter_the_absolute_path_of_the_directory_your_gif_files_are_stored_in {
            get {
                return ResourceManager.GetString("Main_Start_Enter_the_absolute_path_of_the_directory_your_gif_files_are_stored_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the absolute path of the directory your .svg files will be stored in.
        /// </summary>
        internal static string Main_Start_Enter_the_absolute_path_of_the_directory_your_svg_files_will_be_stored_in {
            get {
                return ResourceManager.GetString("Main_Start_Enter_the_absolute_path_of_the_directory_your_svg_files_will_be_stored" +
                        "_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the absolute path of your .gif file.
        /// </summary>
        internal static string Main_Start_Enter_the_absolute_path_of_your_gif_file {
            get {
                return ResourceManager.GetString("Main_Start_Enter_the_absolute_path_of_your_gif_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the absolute path the output .svg file.
        /// </summary>
        internal static string Main_Start_Enter_the_absolute_path_the_output_svg_file {
            get {
                return ResourceManager.GetString("Main_Start_Enter_the_absolute_path_the_output_svg_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Provided path was null, the program will now exit..
        /// </summary>
        internal static string Main_Start_Error_Provided_path_was_null_the_program_will_now_exit_ {
            get {
                return ResourceManager.GetString("Main_Start_Error_Provided_path_was_null_the_program_will_now_exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ########## GIF 2 SVG Converter ##########.
        /// </summary>
        internal static string Main_Start_GIF_2_SVG_Converter {
            get {
                return ResourceManager.GetString("Main_Start_GIF_2_SVG_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple gifs conversion.
        /// </summary>
        internal static string Main_Start_Multiple_gifs_conversion {
            get {
                return ResourceManager.GetString("Main_Start_Multiple_gifs_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .gif files detected in provided directory, try again.
        /// </summary>
        internal static string Main_Start_No_gif_files_detected_in_provided_directory_try_again {
            get {
                return ResourceManager.GetString("Main_Start_No_gif_files_detected_in_provided_directory_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string Main_Start_Select_an_option {
            get {
                return ResourceManager.GetString("Main_Start_Select_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single gif conversion.
        /// </summary>
        internal static string Main_Start_Single_gif_conversion {
            get {
                return ResourceManager.GetString("Main_Start_Single_gif_conversion", resourceCulture);
            }
        }
    }
}
